version: "3"
networks:
  loki:
services:
  loki:
    image: grafana/loki:3.0.0
    volumes:
      - /home/rohit/Desktop/DevOps/Learn/5. Monitaring/loki:/etc/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki
  promtail:
    image: grafana/promtail:3.0.0
    volumes:
      - /var/log:/var/log
      - /home/rohit/Desktop/DevOps/Learn/5. Monitaring/promtail:/etc/promtail
    # ports:
    #   - "1514:1514" # this is only needed if you are going to send syslogs
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki
  grafana:
    image: grafana/grafana:latest
    user: "1000"
    volumes:
    - /home/rohit/Desktop/DevOps/Learn/5. Monitaring/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - loki